import HeroSection from "@/components/HeroSection";
import FeatureCard from "@/components/FeatureCard";
import CTASection from "@/components/CTASection";
import TechBadge from "@/components/TechBadge";
import { Search, BrainCircuit, Target, MessageCircle } from "lucide-react";

export default function Home() {
  return (
    <>
      <HeroSection />

      {/* What is Food-Stat */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="max-w-3xl mx-auto">
            <h2 className="text-3xl font-bold text-gray-900 mb-6">What is Food-Stat?</h2>
            <p className="text-lg text-gray-600 leading-relaxed">
              Food-Stat is an AI-powered nutrition assistant that goes beyond simple calorie counting.
              We use advanced Large Language Models to analyze food items, providing
              <span className="font-semibold text-teal-600"> explainable nutrition scores</span>,
              <span className="font-semibold text-teal-600"> transparent reasoning</span>, and
              <span className="font-semibold text-teal-600"> context-aware recommendations</span> tailored to your specific needs.
            </p>
          </div>
        </div>
      </section>

      {/* Core Features */}
      <section className="py-20 bg-gray-50/50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">Core Capabilities</h2>
            <p className="text-gray-500">Everything you need to make smarter food choices</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            <FeatureCard
              icon={Search}
              title="Custom Scoring"
              description="Expert-level nutrition analysis with transparent reasoning based on scientific data."
            />
            <FeatureCard
              icon={BrainCircuit}
              title="AI Explanations"
              description="Clear, human-readable justifications for every score, generated by advanced LLMs."
            />
            <FeatureCard
              icon={Target}
              title="Context-Aware"
              description="Tailored insights for pregnant mothers, infants, athletes, and weight management."
            />
            <FeatureCard
              icon={MessageCircle}
              title="Food Chatbot"
              description="Ask natural questions about any food item and get instant, detailed insights."
            />
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section id="how-it-works" className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">How It Works</h2>
            <p className="text-gray-500">Get insights in three simple steps</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 relative">
            {/* Connector Line (Desktop) */}
            <div className="hidden md:block absolute top-12 left-[20%] right-[20%] h-0.5 bg-gray-100 -z-10"></div>

            <div className="text-center bg-white p-6">
              <div className="w-16 h-16 bg-teal-50 rounded-full flex items-center justify-center text-xl font-bold text-teal-600 mx-auto mb-6 border-4 border-white shadow-sm">1</div>
              <h3 className="text-xl font-bold mb-3">Enter Food Item</h3>
              <p className="text-gray-500">Simply type in what you&apos;re eating or scan a barcode.</p>
            </div>

            <div className="text-center bg-white p-6">
              <div className="w-16 h-16 bg-teal-50 rounded-full flex items-center justify-center text-xl font-bold text-teal-600 mx-auto mb-6 border-4 border-white shadow-sm">2</div>
              <h3 className="text-xl font-bold mb-3">AI Analysis</h3>
              <p className="text-gray-500">Our LLM reasoning engine analyzes nutritional profile contextually.</p>
            </div>

            <div className="text-center bg-white p-6">
              <div className="w-16 h-16 bg-teal-50 rounded-full flex items-center justify-center text-xl font-bold text-teal-600 mx-auto mb-6 border-4 border-white shadow-sm">3</div>
              <h3 className="text-xl font-bold mb-3">Get Insights</h3>
              <p className="text-gray-500">Receive a detailed score, explanation, and recommendation.</p>
            </div>
          </div>
        </div>
      </section>

      {/* Use Cases */}
      <section id="use-cases" className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">Built For Everyone</h2>
            <p className="text-gray-500">Who benefits from Food-Stat?</p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            <div className="bg-white p-8 rounded-2xl shadow-sm text-center">
              <span className="block text-4xl mb-4">🎓</span>
              <h3 className="font-bold text-lg mb-2">Nutrition Students</h3>
              <p className="text-sm text-gray-500">Verify logic and learn from detailed breakdowns.</p>
            </div>
            <div className="bg-white p-8 rounded-2xl shadow-sm text-center">
              <span className="block text-4xl mb-4">🥗</span>
              <h3 className="font-bold text-lg mb-2">Health Enthusiasts</h3>
              <p className="text-sm text-gray-500">Optimize diet with precision and clarity.</p>
            </div>
            <div className="bg-white p-8 rounded-2xl shadow-sm text-center">
              <span className="block text-4xl mb-4">💪</span>
              <h3 className="font-bold text-lg mb-2">Fitness Coaches</h3>
              <p className="text-sm text-gray-500">Explain diet choices to clients effectively.</p>
            </div>
            <div className="bg-white p-8 rounded-2xl shadow-sm text-center">
              <span className="block text-4xl mb-4">👶</span>
              <h3 className="font-bold text-lg mb-2">Parents</h3>
              <p className="text-sm text-gray-500">Ensure safe and healthy choices for children.</p>
            </div>
          </div>
        </div>
      </section>

      {/* Tech Stack */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <p className="text-sm font-semibold tracking-wider text-gray-500 uppercase mb-8">Powered by modern tech</p>
          <div className="flex flex-wrap justify-center gap-4">
            <TechBadge name="Python" color="bg-blue-50 text-blue-700" />
            <TechBadge name="Flask" color="bg-gray-100 text-gray-700" />
            <TechBadge name="Gemini LLM" color="bg-purple-50 text-purple-700" />
            <TechBadge name="LangChain" color="bg-green-50 text-green-700" />
            <TechBadge name="QdrantDB" color="bg-red-50 text-red-700" />
            <TechBadge name="Next.js" color="bg-black text-white" />
          </div>
        </div>
      </section>

      <CTASection />
    </>
  );
}
